In [6]:
a=[1,2,3]#without using append function
b=len(a)
a[b-1:]=[10]
print(a)

TypeError: can only assign an iterable

In [14]:
import numpy
a=[1,2,3,4,5]
b=[6,7,8]
c=numpy.array(a)
print(c.ndim)
print(c.shape)#


1
(5,)


In [8]:
import numpy#if it is not working keep ipip install numpy
a=[1,2,3,4,5]
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [22]:
import numpy
a=([[1,2,3],[7,8,9,]])
b=[6,7,8]
c=numpy.array(a)
print(c.ndim)
print(c.shape)#
print(c)
print(c.size)

2
(2, 3)
[[1 2 3]
 [7 8 9]]
6


In [23]:
import numpy
a=([[[1,2,3],[7,8,9,],[4,5,6]]])
b=[6,7,8]
c=numpy.array(a)
print(c.ndim)
print(c.shape)#
print(c)
print(c.size)

3
(1, 3, 3)
[[[1 2 3]
  [7 8 9]
  [4 5 6]]]
9


In [24]:
#ascessing values
a=[1,2,3,4]
c=numpy.array(a)
print(c[3])

4


In [26]:
#i want to ascess 5
a=([[1,2,3],[4,5,6]])
c=numpy.array(a)
print(c[1][1])
print(c[0][2])


5
3


In [31]:
a=([[[1,2,3],[4,5,6]]])
c=numpy.array(a)
print(c)
print(c.shape)
# i want to get 6
print(c[0][1][2])

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
6


In [47]:
#arrange 
import numpy
a=10
for i in range(1,a+1):
    print(i,end=' ')
#by arrange function
print('')
b=numpy.arange(1,11)
print(b)


1 2 3 4 5 6 7 8 9 10 
[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
#Line space
import numpy
a=numpy.linspace(10,20,5)
print(a)

[10.  12.5 15.  17.5 20. ]


In [44]:
#Zeros
import numpy
a=numpy.zeros((3,2),dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [45]:
#ones
d=numpy.ones((3,3),dtype=int)
print(d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
c=numpy.arange(1,61)
d=c.reshape(10,6)
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [55]:
c1=c.reshape(5,2,6)
print(c1)
print(c1[4][0][4])

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
53


In [63]:
#axis
# for rows axis is 1
#for columns axis is 0
a=numpy.arange(1,61).reshape(10,6)
print(a)
print(a.sum(1))#rows  sum
print(a.sum(0))#columns sum
a.sum(axis=1)
print(a[1].sum())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
[ 21  57  93 129 165 201 237 273 309 345]
[280 290 300 310 320 330]
57


In [67]:
a=numpy.arange(1,61).reshape(10,6)
print(a.shape)
b=numpy.arange(1,61).reshape(10,6)
print(b.shape)
c=numpy.vstack((a,b))
print(c.shape)
print(c)
d=numpy.hstack((a,b))
print(d)

(10, 6)
(10, 6)
(20, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
[[ 1  2  3  4  5  6  1  2  3  4  5  6]
 [ 7  8  9 10 11 12  7  8  9 10 11 12]
 [13 14 15 16 17 18 13 14 15 16 17 18]
 [19 20 21 22 23 24 19 20 21 22 23 24]
 [25 26 27 28 29 30 25 26 27 28 29 30]
 [31 32 33 34 35 36 31 32 33 34 35 36]
 [37 38 39 40 41 42 37 38 39 40 41 42]
 [43 44 45 46 47 48 43 44 45 46 47 48]
 [49 50 51 52 53 54 49 50 51 52 53 54]
 [55 56 57 58 59 60 55 56 57 58 59 60]]


In [69]:
#diag
a=[1,2,3]
c=numpy.diag(a)
print(c)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [75]:
#transpose
a=([[1,2,3],[4,5,6]])
e=([[7,8,9],[9,8,7]])
b=numpy.array(a)
c=numpy.concatenate((a,b))
print(c)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [3]:
import numpy
a=[10,20,30,40,]
c=numpy.array(a)
print(numpy.sum(c))
print(numpy.exp(c))

100
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [8]:
#randm
numpy.random.randint(10,100)
numpy.random.rand(3,4)
numpy.random.randn(3,4)

array([[ 0.30632951, -0.63757096,  0.33884499, -0.5071213 ],
       [ 1.18464689, -0.35920349,  0.2928119 , -0.99778388],
       [ 1.12128585,  0.3108014 ,  0.30885619, -0.7552511 ]])

In [7]:
numpy.__version__


'1.21.5'

In [13]:
#full method
numpy.full((5,5),'jaga',dtype=str)

array([['j', 'j', 'j', 'j', 'j'],
       ['j', 'j', 'j', 'j', 'j'],
       ['j', 'j', 'j', 'j', 'j'],
       ['j', 'j', 'j', 'j', 'j'],
       ['j', 'j', 'j', 'j', 'j']], dtype='<U1')

In [14]:
#filter 
a=[10,20,30,40,50]
c=numpy.array(a)
print(c)

[10 20 30 40 50]


In [19]:
a=numpy.array([[10,20,30,40,50],[100,200,300,400,500]])
print(a)
print()
print(a>300)
print(a.shape)
print(a.size)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]

[[False False False False False]
 [False False False  True  True]]
(2, 5)
10


In [26]:
#arthemetic operations
a=numpy.array([[10,20,30,40,50],[100,200,300,400,500]])
b=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a+b)
print(numpy.add(a,b))
print(numpy.multiply(a,b))
print(numpy.divide(a,b))

[[ 11  22  33  44  55]
 [106 207 308 409 510]]
[[ 11  22  33  44  55]
 [106 207 308 409 510]]
[[  10   40   90  160  250]
 [ 600 1400 2400 3600 5000]]
[[10.         10.         10.         10.         10.        ]
 [16.66666667 28.57142857 37.5        44.44444444 50.        ]]


In [28]:
b=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b.size)
c=0
for i in b:
    for j in i:
        c=c+1
print(c)
        

10
10


In [32]:
numpy.mean(b)
print(numpy.mean(b,axis=0))
numpy.mean(b,axis=1)#rows

[3.5 4.5 5.5 6.5 7.5]


array([3., 8.])

In [43]:
a=[10,3,4,5,2,3]
a.sort()
a.sort(reverse=True)
print(a)
print(a[::-1])

[10, 5, 4, 3, 3, 2]
[2, 3, 3, 4, 5, 10]


In [45]:
#sorting with numpy
b=numpy.array([[1,2,3,4,5],[6,10,9,8,7]])
print(b)
print(numpy.sort(b))
print(numpy.sort(b)[::-1])

[[ 1  2  3  4  5]
 [ 6 10  9  8  7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [48]:
#3 dimension
a=numpy.arange(1,61)
c=a.reshape(5,2,6)
print(c)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [50]:
c[2][1][1]#2=rowss,1=cube face,1=column

32

In [1]:
#identity matrix
import numpy as np
a=np.eye(5,5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
